CREATE OR REPLACE TRIGGER TRG_AMISTAD_NO_AUTO
BEFORE INSERT OR UPDATE ON AMISTAD
FOR EACH ROW
BEGIN
  IF :NEW.IDUSUARIO1 = :NEW.IDUSUARIO2 THEN
    RAISE_APPLICATION_ERROR(-20001, 'No se permite que un usuario sea amigo de sí mismo.');
  END IF;
END;
/
